version = "3.8.4"

runner.dialect = scala3

maxColumn = 100

rewrite.rules = [Imports]
rewrite.imports.sort = ascii
rewrite.imports.groups = [
  ["cats\\..*"],
  ["org.typelevel.log4cats\\..*"],
  ["pureconfig\\..*"],
  ["io.circe\\..*"],
  ["org.http4s\\..*"],
  ["doobie\\..*"],
  ["dev.profunktor.redis4cats\\..*"],
  ["org.scalatest\\..*"],
  [".*"],
  ["scala\\..*"],
  ["java\\..*", "javax\\..*"],
  ["com.endsoullab\\..*"]
]
